#!/bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc rule -a Firefox desktop=^4
bspc rule -a scratchpad floating=on sticky=on center=on
bspc rule -a Nautilus floating=on

bspc config border_width	1
bspc config window_gap		1
bspc config split_ratio		0.5
bspc config borderless_monocle	true
bspc config gapless_monocle	true

bspc config top_padding		42

bspc control --subscribe > $PANEL_FIFO &
